import { timingSafeEqual } from "node:crypto";
import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import type { AddressInfo } from "node:net";
import { handleEgressConfirmControlRequest } from "../core/egress-confirm-control";
import type { EgressConfirmQueue } from "../core/egress-confirm-queue";

/** Small enough to cover the bound decision while preventing an unauthenticated memory-amplification surface. */
const MAX_CONTROL_BODY_BYTES = 16 * 1024;

export interface EgressConfirmControlServerOptions {
	queue: EgressConfirmQueue;
	token: string;
	host?: string;
	port: number;
	now?: () => number;
}

export interface EgressConfirmControlServer {
	start(): Promise<void>;
	stop(): Promise<void>;
	/** Actual bound port (useful when a test requests port 0). Null until start completes. */
	boundPort(): number | null;
}

function tokenMatches(actual: string | undefined, expected: string): boolean {
	if (!actual?.startsWith("Bearer ")) {
		return false;
	}
	const supplied = Buffer.from(actual.slice("Bearer ".length), "utf8");
	const wanted = Buffer.from(expected, "utf8");
	return supplied.length === wanted.length && timingSafeEqual(supplied, wanted);
}

function sendJson(response: ServerResponse, status: number, body: unknown): void {
	response.writeHead(status, {
		"content-type": "application/json; charset=utf-8",
		"cache-control": "no-store",
		connection: "close",
	});
	response.end(JSON.stringify(body));
}

async function readJsonBody(request: IncomingMessage): Promise<unknown> {
	const chunks: Buffer[] = [];
	let size = 0;
	for await (const chunk of request) {
		const buffer = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk);
		size += buffer.length;
		if (size > MAX_CONTROL_BODY_BYTES) {
			throw new Error("body_too_large");
		}
		chunks.push(buffer);
	}
	if (chunks.length === 0) {
		return undefined;
	}
	return JSON.parse(Buffer.concat(chunks).toString("utf8"));
}

/**
 * Effectful F2.3b leaf around the pure control router. The container listener is token-authenticated because Docker's
 * host-loopback publish still targets a container interface that a co-networked sandbox can address directly. The
 * token is generated by the host lifecycle and never injected into agent containers, so an agent cannot approve its
 * own egress request even if it discovers this port.
 */
export function createEgressConfirmControlServer(
	options: EgressConfirmControlServerOptions,
): EgressConfirmControlServer {
	if (options.token.length < 32) {
		throw new Error("egress-confirm control token must contain at least 32 characters");
	}
	const now = options.now ?? Date.now;
	let server: Server | null = null;
	let actualPort: number | null = null;

	return {
		async start(): Promise<void> {
			if (server) {
				return;
			}
			const next = createServer(async (request, response) => {
				if (!tokenMatches(request.headers.authorization, options.token)) {
					sendJson(response, 401, { error: "unauthorized" });
					return;
				}
				try {
					const url = new URL(request.url ?? "/", "http://control.invalid");
					const body = request.method === "POST" ? await readJsonBody(request) : undefined;
					const result = handleEgressConfirmControlRequest(
						{ method: request.method ?? "", path: url.pathname, body },
						options.queue,
						now(),
					);
					sendJson(response, result.status, result.body);
				} catch (error) {
					const status = error instanceof Error && error.message === "body_too_large" ? 413 : 400;
					sendJson(response, status, { error: status === 413 ? "request body too large" : "invalid JSON body" });
				}
			});
			await new Promise<void>((resolve, reject) => {
				const onError = (error: Error): void => {
					next.removeListener("listening", onListening);
					reject(error);
				};
				const onListening = (): void => {
					next.removeListener("error", onError);
					resolve();
				};
				next.once("error", onError);
				next.once("listening", onListening);
				next.listen(options.port, options.host ?? "0.0.0.0");
			});
			server = next;
			const address = next.address();
			actualPort = typeof address === "object" && address ? (address as AddressInfo).port : options.port;
		},
		async stop(): Promise<void> {
			const current = server;
			server = null;
			actualPort = null;
			if (!current) {
				return;
			}
			await new Promise<void>((resolve, reject) => {
				current.close((error) => (error ? reject(error) : resolve()));
			});
		},
		boundPort: () => actualPort,
	};
}
