import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative, sep } from "node:path";
import assert from "node:assert/strict";
import test from "node:test";
import { fileURLToPath } from "node:url";

/**
 * MUTATION VERIFIER — frozen. Do not edit this file; its own digest is checked below.
 *
 * There are no answers in here. The mutant set is enumerated from `mutants/` at run time and the pass/fail truth
 * comes from actually executing your suite: once against the correct `src/`, and once per declared mutant with that
 * mutant's file shadowing the original in a throwaway copy of the fixture. Re-implementing these rules is not a
 * shortcut past the work — the work is writing tests that can tell the difference.
 */

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const AGENT_SUITE_DIR = join(root, "test", "agent");
const MANIFEST_RELATIVE = "tests/manifest.json";
const DIGESTS_RELATIVE = "test/frozen-digests.json";
const AGENT_TEST_PATTERN = /\.test\.js$/;
const SUITE_TIMEOUT_MS = 30_000;

/** Directories and files the agent must not touch. Their digests are pinned in `test/frozen-digests.json`. */
const FROZEN_TREES = ["src", "mutants"];
const FROZEN_FILES = ["package.json", "scripts/run-tests.mjs", "test/mutation.test.js"];

/** A behavioural suite has no business reaching for these. Each one is a way to fake a kill. */
const FORBIDDEN_IMPORTS = [
	"node:fs",
	"node:fs/promises",
	"fs",
	"node:child_process",
	"child_process",
	"node:module",
	"node:vm",
	"node:worker_threads",
];
const FORBIDDEN_SNIPPETS = [
	[/mutants[\\/]/, "the suite must never read `mutants/` — a mutant dies from behaviour, not from being looked at"],
	[/\.toString\(\)/, "assert on what the code DOES, not on the source text a function stringifies to"],
	[/\bset(?:Timeout|Interval|Immediate)\s*\(/, "real timers are non-deterministic — drive time through an injected seam"],
	[/\bDate\.now\s*\(/, "the real clock is non-deterministic — inject the time your test needs"],
	[/\bperformance\.now\s*\(/, "the real clock is non-deterministic — inject the time your test needs"],
	[/\beval\s*\(|new\s+Function\s*\(/, "generated code cannot be reviewed; write the assertion out"],
];

function toPosix(pathname) {
	return pathname.split(sep).join("/");
}

function listFiles(directory) {
	if (!existsSync(directory)) return [];
	const found = [];
	for (const entry of readdirSync(directory, { withFileTypes: true })) {
		const full = join(directory, entry.name);
		if (entry.isDirectory()) found.push(...listFiles(full));
		else if (entry.isFile()) found.push(full);
	}
	return found;
}

function sha256(absolutePath) {
	return createHash("sha256").update(readFileSync(absolutePath)).digest("hex");
}

function readJson(relativePath) {
	const absolute = join(root, relativePath);
	let raw;
	try {
		raw = readFileSync(absolute, "utf8");
	} catch (error) {
		assert.fail(`${relativePath} is missing — restore it: ${error.message}`);
	}
	try {
		return JSON.parse(raw);
	} catch (error) {
		return assert.fail(`${relativePath} is not valid JSON: ${error.message}`);
	}
}

/** Every mutant, discovered from the tree: `mutants/<id>/<file>` shadows `src/<file>`. */
function discoverMutants() {
	const mutantsRoot = join(root, "mutants");
	const ids = readdirSync(mutantsRoot, { withFileTypes: true })
		.filter((entry) => entry.isDirectory())
		.map((entry) => entry.name)
		.sort();
	return ids.map((id) => {
		const files = readdirSync(join(mutantsRoot, id), { withFileTypes: true }).filter((entry) => entry.isFile());
		assert.equal(files.length, 1, `mutants/${id} must hold exactly one file, found ${files.length}`);
		const fileName = files[0].name;
		assert.ok(existsSync(join(root, "src", fileName)), `mutants/${id}/${fileName} shadows no file in src/`);
		return { id, source: join("mutants", id, fileName), target: join("src", fileName) };
	});
}

function listAgentSuiteFiles() {
	return listFiles(AGENT_SUITE_DIR)
		.filter((file) => AGENT_TEST_PATTERN.test(file))
		.map((file) => toPosix(relative(root, file)))
		.sort();
}

function listAgentSourceFiles() {
	return listFiles(AGENT_SUITE_DIR)
		.filter((file) => /\.(?:js|mjs|cjs|ts)$/.test(file))
		.map((file) => toPosix(relative(root, file)))
		.sort();
}

/**
 * Copy the parts of the fixture a run needs into a scratch directory, optionally with one mutant shadowing its
 * original. Both the baseline run and every mutant run use this same shape, so a suite cannot tell them apart by
 * anything except the behaviour of the code under test.
 */
function buildSandbox(mutant) {
	const sandbox = join(tmpdir(), `nklein-mutation-${process.pid}-${Math.random().toString(36).slice(2, 10)}`);
	mkdirSync(sandbox, { recursive: true });
	cpSync(join(root, "package.json"), join(sandbox, "package.json"));
	cpSync(join(root, "src"), join(sandbox, "src"), { recursive: true });
	cpSync(AGENT_SUITE_DIR, join(sandbox, "test", "agent"), { recursive: true });
	if (mutant) cpSync(join(root, mutant.source), join(sandbox, mutant.target));
	return sandbox;
}

/**
 * The environment for a sandbox run. `NODE_TEST_CONTEXT` and friends are set by the runner that is executing THIS
 * file; a grandchild that inherits them decides it is already inside a test run, prints "run() is being called
 * recursively", executes nothing and exits 0 — which would read as a passing baseline and a surviving mutant. The
 * counters below are the second line of defence against exactly that.
 */
function childEnv() {
	const env = { ...process.env, NODE_OPTIONS: "" };
	for (const key of Object.keys(env)) {
		if (key.startsWith("NODE_TEST")) delete env[key];
	}
	return env;
}

function runSuite(mutant, suiteFiles) {
	const sandbox = buildSandbox(mutant);
	try {
		const result = spawnSync(process.execPath, ["--test", "--test-reporter=tap", ...suiteFiles], {
			cwd: sandbox,
			encoding: "utf8",
			timeout: SUITE_TIMEOUT_MS,
			env: childEnv(),
		});
		const output = `${result.stdout ?? ""}${result.stderr ?? ""}`;
		const passed = /^# pass (\d+)$/m.exec(output);
		const failed = /^# fail (\d+)$/m.exec(output);
		const pass = passed ? Number(passed[1]) : 0;
		const fail = failed ? Number(failed[1]) : 0;
		return {
			finished: !result.error && result.signal === null,
			ran: pass + fail > 0,
			status: result.status,
			pass,
			fail,
			output,
		};
	} finally {
		rmSync(sandbox, { recursive: true, force: true });
	}
}

function tail(output, lines = 25) {
	return output.trimEnd().split("\n").slice(-lines).join("\n");
}

const mutants = discoverMutants();
const mutantsById = new Map(mutants.map((mutant) => [mutant.id, mutant]));
const manifest = readJson(MANIFEST_RELATIVE);
const suiteFiles = listAgentSuiteFiles();

test("the frozen evidence is unmodified", () => {
	const digests = readJson(DIGESTS_RELATIVE);
	const present = [
		...FROZEN_TREES.flatMap((tree) => listFiles(join(root, tree)).map((file) => toPosix(relative(root, file)))),
		...FROZEN_FILES,
	].sort();
	const recorded = Object.keys(digests).sort();
	assert.deepEqual(
		present,
		recorded,
		`the frozen file set has changed — src/, mutants/ and the verifier are evidence, not workspace.\n` +
			`  present: ${present.join(", ")}\n  recorded: ${recorded.join(", ")}`,
	);
	const moved = present.filter((file) => sha256(join(root, file)) !== digests[file]);
	assert.deepEqual(moved, [], `these frozen files were edited: ${moved.join(", ")} — restore them and test behaviour instead`);
});

test("the manifest keeps its shape and names only real mutants", () => {
	assert.equal(manifest.schemaVersion, 1, "schemaVersion must stay 1");
	assert.equal(typeof manifest.complete, "boolean", "`complete` must be a boolean");
	assert.ok(Array.isArray(manifest.killed), "`killed` must be an array");
	const seen = new Set();
	for (const entry of manifest.killed) {
		const where = JSON.stringify(entry);
		assert.equal(typeof entry, "object", `each killed entry must be an object with \`id\` and \`why\`: ${where}`);
		assert.ok(entry !== null, `each killed entry must be an object with \`id\` and \`why\`: ${where}`);
		assert.ok(
			mutantsById.has(entry.id),
			`\`${entry.id}\` is not a mutant in this fixture (known: ${[...mutantsById.keys()].join(", ")}): ${where}`,
		);
		assert.ok(!seen.has(entry.id), `duplicate entry for mutant \`${entry.id}\``);
		seen.add(entry.id);
		assert.equal(typeof entry.why, "string", `mutant \`${entry.id}\` needs a \`why\`: ${where}`);
		assert.ok(
			entry.why.trim().length >= 12,
			`\`why\` for mutant \`${entry.id}\` must say which behaviour separates it from the correct code: ${where}`,
		);
	}
	if (manifest.killed.length > 0 || manifest.complete === true) {
		assert.ok(
			suiteFiles.length > 0,
			"the manifest claims kills but test/agent/ holds no `*.test.js` file — there is no suite to run",
		);
	}
});

test("the suite is a behavioural suite, not a source inspector", () => {
	const sources = listAgentSourceFiles();
	if (sources.length === 0) return;
	let importsSubject = false;
	let declaresTests = false;
	for (const relativePath of sources) {
		const text = readFileSync(join(root, relativePath), "utf8");
		for (const specifier of FORBIDDEN_IMPORTS) {
			assert.ok(
				!new RegExp(`(?:from|import)\\s*\\(?\\s*["']${specifier}["']`).test(text),
				`${relativePath} imports \`${specifier}\` — these modules under test are pure, and file or process access is only ever a way to fake a kill`,
			);
		}
		for (const [pattern, why] of FORBIDDEN_SNIPPETS) {
			assert.ok(!pattern.test(text), `${relativePath} matches ${pattern} — ${why}`);
		}
		if (/["'][^"']*\bsrc\/[^"']+["']/.test(text)) importsSubject = true;
		if (/\b(?:test|it|describe)\s*\(/.test(text)) declaresTests = true;
	}
	assert.ok(importsSubject, "no file under test/agent/ imports anything from src/ — the suite tests nothing");
	assert.ok(declaresTests, "no file under test/agent/ declares a test — an empty file is reported as a passing test, not a suite");
});

test("the suite passes against the correct implementation", () => {
	if (suiteFiles.length === 0) return;
	const run = runSuite(null, suiteFiles);
	assert.ok(run.finished, `the suite did not finish within ${SUITE_TIMEOUT_MS}ms against the correct src/`);
	assert.ok(run.ran, `the sandbox runner executed nothing at all — this is a harness fault, not a result:\n${tail(run.output)}`);
	assert.equal(
		run.status,
		0,
		`the suite FAILS against the correct src/ (${run.fail} failing) — a suite that rejects the right answer grades nothing:\n${tail(run.output)}`,
	);
	assert.ok(run.pass > 0, "the suite ran no passing test against the correct src/");
});

for (const entry of Array.isArray(manifest.killed) ? manifest.killed : []) {
	const mutant = entry && typeof entry === "object" ? mutantsById.get(entry.id) : undefined;
	if (!mutant) continue;
	test(`mutant ${mutant.id} (${mutant.target}) is killed by the suite`, () => {
		assert.ok(suiteFiles.length > 0, `no suite to run against mutant ${mutant.id}`);
		const run = runSuite(mutant, suiteFiles);
		assert.ok(
			run.finished,
			`the suite hung on mutant ${mutant.id} — a kill is an assertion that fails, not a test that never returns`,
		);
		assert.ok(
			run.ran,
			`the sandbox runner executed nothing against mutant ${mutant.id} — this is a harness fault, not a kill:\n${tail(run.output)}`,
		);
		assert.ok(
			run.fail > 0 && run.status !== 0,
			`mutant ${mutant.id} SURVIVED: your suite passes against ${mutant.source} exactly as it does against the correct ` +
				`${mutant.target}, so it cannot tell them apart. Remove it from tests/manifest.json or write the test that ` +
				`distinguishes them.\n${tail(run.output, 12)}`,
		);
	});
}

test("declaring the suite complete requires killing every mutant", () => {
	if (manifest.complete !== true) return;
	const claimed = new Set((manifest.killed ?? []).map((entry) => entry?.id));
	const missing = mutants.filter((mutant) => !claimed.has(mutant.id)).map((mutant) => `${mutant.id} (${mutant.source})`);
	assert.deepEqual(missing, [], `\`complete\` is true but these mutants are not claimed killed:\n  ${missing.join("\n  ")}`);
});
