export const NKLEIN_HOME_DIR_NAME = ".nklein";
export const NKLEIN_RUNTIME_DIR_NAME = "nklein";
export const LEGACY_KANBAN_RUNTIME_DIR_NAME = "kanban";
export const NKLEIN_RUNTIME_HOME_DIR_NAME = `${NKLEIN_HOME_DIR_NAME}/${NKLEIN_RUNTIME_DIR_NAME}`;
export const LEGACY_KANBAN_RUNTIME_HOME_DIR_NAME = `${NKLEIN_HOME_DIR_NAME}/${LEGACY_KANBAN_RUNTIME_DIR_NAME}`;
export const NKLEIN_PROJECT_CONFIG_DIR_NAME = NKLEIN_RUNTIME_DIR_NAME;
export const TASK_WORKTREES_HOME_DIR_NAME = `${NKLEIN_HOME_DIR_NAME}/worktrees`;
export const TASK_WORKTREES_DIR_NAME = "worktrees";
