/**
 * P20.3b — the EFFECTFUL half of the no-op ablation: stub an artifact so it FAILS LOUDLY, re-run the same test
 * selection, and emit the two `{testId, passed}` JSONL files that `dev ablation` already judges.
 *
 *   tsx scripts/ablate.mts --module src/core/foo.ts --tests test/runtime/core/foo.test.ts --out-dir .ablation
 *   nklein dev ablation --baseline .ablation/baseline.jsonl --ablated .ablation/ablated.jsonl
 *
 * ── WHY THE STUB THROWS FROM EVERY EXPORT ──
 * A stub returning `null`, `0`, `[]` or `""` lets tests pass for the WRONG reason: an artifact that is genuinely
 * load-bearing but tolerant of empty input comes back `DECORATIVE`, and someone deletes working code on the
 * strength of it. That is the expensive direction of this measurement, so every stubbed entry point throws —
 * functions when called, values when read (via a throwing getter, since a plain `undefined` is exactly the
 * plausible default this exists to avoid).
 *
 * ── WHY THE SELECTION IS FIXED ONCE ──
 * The ablated run must exercise the SAME tests as the baseline. Re-deriving the selection after stubbing would
 * let a collection error silently shrink it, and a smaller all-green run reads as "nothing depended on this".
 * The selection is therefore computed once, and a run whose test COUNT changed is reported rather than judged.
 *
 * The original module is restored in a `finally`, and the restore is verified — leaving a repo stubbed would be
 * a far worse failure than any verdict this produces.
 */

import { execFile } from "node:child_process";
import { existsSync } from "node:fs";
import { copyFile, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

function arg(name: string): string | undefined {
	const index = process.argv.indexOf(`--${name}`);
	return index === -1 ? undefined : process.argv[index + 1];
}

const modulePath = arg("module");
const testSelection = arg("tests");
const outDir = arg("out-dir") ?? ".ablation";
if (!modulePath || !testSelection) {
	process.stderr.write("usage: ablate.mts --module <src/...ts> --tests <test pattern> [--out-dir <dir>]\n");
	process.exit(64);
}

/** Run vitest over a fixed selection and reduce its JSON report to the `{testId, passed}` shape. */
async function runSelection(label: string): Promise<Array<{ testId: string; passed: boolean }>> {
	const reportPath = join(outDir, `${label}-report.json`);
	try {
		await execFileAsync(
			"npx",
			["vitest", "run", testSelection as string, "--reporter=json", `--outputFile=${reportPath}`],
			{ maxBuffer: 64 * 1024 * 1024, timeout: 15 * 60_000 },
		);
	} catch {
		// A failing suite is the EXPECTED outcome of the ablated run; the report is what matters, not the exit code.
	}
	if (!existsSync(reportPath)) {
		throw new Error(`${label}: vitest produced no report at ${reportPath} — the selection may not have collected`);
	}
	const report = JSON.parse(await readFile(reportPath, "utf8")) as {
		testResults?: Array<{ name: string; assertionResults?: Array<{ fullName?: string; title?: string; status: string }> }>;
	};
	const rows: Array<{ testId: string; passed: boolean }> = [];
	for (const file of report.testResults ?? []) {
		for (const assertion of file.assertionResults ?? []) {
			rows.push({
				testId: `${file.name}::${assertion.fullName ?? assertion.title ?? "?"}`,
				passed: assertion.status === "passed",
			});
		}
	}
	return rows;
}

const writeJsonl = async (path: string, rows: readonly { testId: string; passed: boolean }[]) =>
	await writeFile(path, `${rows.map((row) => JSON.stringify(row)).join("\n")}\n`, "utf8");

/** A stub whose every export fails loudly — functions on call, values on READ. */
async function buildThrowingStub(target: string): Promise<string> {
	const loaded = (await import(pathToFileURL(resolve(target)).href)) as Record<string, unknown>;
	const names = Object.keys(loaded).filter((name) => name !== "default");
	const marker = `ABLATED_STUB: ${target} was stubbed by scripts/ablate.mts and must not be reachable`;
	const lines = [
		`// AUTO-GENERATED by scripts/ablate.mts — the original is restored in a finally block.`,
		`const fail = (name) => { throw new Error(\`${marker} (via \${name})\`); };`,
	];
	for (const name of names) {
		if (typeof loaded[name] === "function") {
			lines.push(`export const ${name} = (...args) => fail(${JSON.stringify(name)});`);
		} else {
			// A throwing GETTER, not `undefined`: a plausible default is the false-accusation path this avoids.
			lines.push(`export const ${name} = new Proxy({}, { get: () => fail(${JSON.stringify(name)}) });`);
		}
	}
	if (names.length === 0) {
		throw new Error(`${target} exports nothing importable — there is nothing to ablate`);
	}
	return `${lines.join("\n")}\n`;
}

await mkdir(outDir, { recursive: true });
const target = resolve(modulePath as string);
const backup = join(outDir, "original.bak");
await mkdir(dirname(backup), { recursive: true });

process.stdout.write(`baseline: running ${testSelection} against the real ${modulePath}…\n`);
const baseline = await runSelection("baseline");
await writeJsonl(join(outDir, "baseline.jsonl"), baseline);
process.stdout.write(`  ${baseline.length} test(s), ${baseline.filter((r) => r.passed).length} passing\n`);

const stub = await buildThrowingStub(modulePath as string);
await copyFile(target, backup);
let restored = false;
try {
	await writeFile(target, stub, "utf8");
	process.stdout.write(`ablated: ${modulePath} stubbed (every export throws); re-running the SAME selection…\n`);
	const ablated = await runSelection("ablated");
	await writeJsonl(join(outDir, "ablated.jsonl"), ablated);
	process.stdout.write(`  ${ablated.length} test(s), ${ablated.filter((r) => r.passed).length} passing\n`);

	if (ablated.length !== baseline.length) {
		// A shrunken selection is NOT a verdict: fewer tests that all pass reads as "nothing depended on this".
		process.stdout.write(
			`\n⚠ the ablated run collected ${ablated.length} test(s) against the baseline's ${baseline.length}. ` +
				"A stub that breaks COLLECTION changes the selection, and a smaller all-green run would read as DECORATIVE. " +
				"Judge this pair only after the counts match.\n",
		);
	}
} finally {
	await copyFile(backup, target);
	restored = (await readFile(target, "utf8")) !== stub;
	await rm(backup, { force: true });
	process.stdout.write(restored ? `restored ${modulePath}\n` : `\n🔴 FAILED TO RESTORE ${modulePath} — restore from ${backup}\n`);
}
if (!restored) {
	process.exit(3);
}
process.stdout.write(
	`\nnow judge them:\n  npx tsx src/cli.ts dev ablation --baseline ${join(outDir, "baseline.jsonl")} --ablated ${join(outDir, "ablated.jsonl")}\n`,
);
